### ISSUE TITLE
Set up error - Graphql query fails on new Prismic repo

### ISSUE THREAD

**Issue by colbisaurusrex** [margueriteroth/gatsby-prismic-starter-prist#5] opened 2019-09-21 16:31 UTC
Hello,

I followed the read-me step by step and created a Prismic repo, linking it gatsby-config.js where it is required. I get a long list of errors when I start the dev server. Is there something I am missing? Pretty new to Prismic/

<img width="1096" alt="Screen Shot 2019-09-21 at 12 27 46 PM" src="https://user-images.githubusercontent.com/18058808/65376222-7db2ec00-dc6b-11e9-9099-ff19483065fd.png">

Do you have any advice? I like the starter kit and would love to use it.

Best,

Colby

**Comment by timrodz** [comment] 2019-09-23 11:22
Ditto. Haven't used Netlify or Prismic before, so I'll try give it a go when I have more time.

**Comment by umriyaafini** [comment] 2019-10-04 09:32
I've experienced the same problem when I change the `repositoryName` in `gatsby-config.js` to my repository name for the project, revert it to `prist` will fix the problem.

```
{
        resolve: 'gatsby-source-prismic-graphql',
        options: {
            repositoryName: 'prist', // (REQUIRED, replace with your own)
            linkResolver: () => post => `/${post.uid}`,
        }
    }
```

**Comment by umriyaafini** [comment] 2019-10-04 12:12
You need to follow all steps in the instruction including a Prismic repository and 3 Custom Types: Project, Post and Project with at least 1 document in each Custom Types.

**Comment by colbisaurusrex** [comment] 2019-10-04 14:03
@umriyaafini Thank you, I have done that and still run into the issue. I created my own Prismic repository, created those custom types and linked it.

**Comment by barbgegrasse** [comment] 2019-10-05 22:52
Hi, same here, 3 custom types, with copy paste of the JSON, and put my repo name in the gatsby config <kovsky-blog>

**Comment by umriyaafini** [comment] 2019-10-06 04:29
Have you created the document/content for each type? 

I think the error caused by empty `allProjects`

**Comment by delacernamarimar** [comment] 2019-10-07 11:28
I already copy-paste the custom types and created some data with it, but the issue is the main page it has an error, but if I browse to http://localhost:8000/blog and http://localhost:8000/work my samples the I created are shown, 

<img width="720" alt="Screen Shot 2019-10-07 at 7 26 39 PM" src="https://user-images.githubusercontent.com/16896411/66307956-685ee280-e938-11e9-8ca4-3f5b05a5e9a5.png">

**Comment by delacernamarimar** [comment] 2019-10-08 06:24
I already make it work by inputting data in prismic and rerun the app after publishing

I hope it works on your end.

**Comment by colbisaurusrex** [comment] 2019-10-08 15:11
@delacernamarimar Did you create your own prismic repo?

**Comment by colbisaurusrex** [comment] 2019-10-08 15:13
@umriyaafini I haven't created any new content - all custom types have a schema, but I haven't created any actual posts, etc

**Comment by delacernamarimar** [comment] 2019-10-08 23:53
@colbisaurusrex yes I created it, create some post so that you can test,

**Comment by aplboi** [comment] 2019-10-24 07:03
Please try @barbgegrasse's advice. It solved my prob. Thank you!
```
gatsby clean
```

**Comment by adamUpchurch** [comment] 2019-10-24 12:20
`gatsby clean` 
Worked for me too!

**Comment by chaserx** [comment] 2019-11-05 02:25
I found some luck with this issue changing the repository security to Open API. Unsure if there's a way to add API credentials. 

<img width="1115" alt="Screen Shot 2019-11-04 at 9 22 51 PM" src="https://user-images.githubusercontent.com/7292/68173553-4ceff300-ff49-11e9-9404-b506bf8ad8d5.png">

**Comment by georgex1999** [comment] 2020-01-24 21:45
I had a bit of trouble setting this up but it's pretty cool now it's running! Thought I would add some things it took me a while to grasp:

- If you, like me, are new to prismic.io.. you can't just setup the Custom types as stated in the readme you also need to add **Content** to them and Publish. This may seem obvious but stumped me for a while!
- As far as I could tell you need to fill in ALL the fields with content to get the site up and running. Otherwise you get a NULL value error.
- I had an error that stumped me for a while and it was because I hadn't added the link properly to the social media link. I'll attach a screenshot of this in case it catches anyone else out and the error it brings up.

<img width="1051" alt="Screenshot 2020-01-24 at 21 32 59" src="https://user-images.githubusercontent.com/25911184/73106023-4e024200-3ef2-11ea-9e8f-4882b92ea953.png">
<img width="1321" alt="Screenshot 2020-01-24 at 21 42 04" src="https://user-images.githubusercontent.com/25911184/73106151-9faacc80-3ef2-11ea-92dd-b7a51bea8fa0.png">

**Comment by jtcarrasco** [comment] 2020-02-07 21:48
having the same issue as everyone has there been any recent updates?

**Comment by croensch** [comment] 2020-03-21 23:35
First, thank you that is an amazing template.
I found out yes, you have to create content for "Post" and "Project" but also "Homepage". For the last one i filled everything but i still get `TypeError: social.about_link[0].spans[0] is undefined` anyone can help?

**Comment by databyjp** [comment] 2020-04-17 10:06
Yup I also had the same issue - resolved by running 
`gatsby clean`

**Comment by JesseSingleton** [comment] 2020-04-23 12:57
@georgex1999 That was super helpful as someone who hadn't used Prismic.

@margueriteroth Really appreciate the template. Can I suggest that someone adds @georgex1999 
 tips as a Tips/Errors section or as steps in the readme. I can look at doing that if you like!

**Comment by kylemhudson** [comment] 2020-07-02 14:27
@margueriteroth thanks so much for this template. Setup was super clear and easy to do. Much appreciated. 

Agree with the above, I'd recommend adding a few more points to the end of "3. Define your Custom Types" telling the user to fill out at least enough content in the Custom Types to populate one of each type, and definitely show adding the URL to the About section. Adding enough content to everything else doesn't do it, you have to add the URL type within About for the project to work. 

Thanks again.

**Comment by marguerrrite** [comment] 2020-07-06 15:39
Thank you @kylemhudson, @georgex1999, @JesseSingleton, and everyone else for outlining this issue and solution. I've added a **Tips & Common Errors** section to the readme and included these items.

**Comment by k-hud** [comment] 2020-07-06 15:40
@margueriteroth amazing, thank you!

**Closed by marguerrrite** 2020-07-06 15:39 UTC

**Comment by br34th3r** [comment] 2020-11-13 14:11
It was `gatsby clean` for me as well, thanks everyone!
